### ISSUE TITLE
Remove rule due to unpairing issue for some users

### ISSUE THREAD

**Issue by fmaguire** [jaleezyy/covid-19-signal#100]
Given that we are generally only using one pool these days can we remove this rule: its a bit fragile and Darian Hole just had an issue of it breaking pairing of already paired reads with slightly different headers.  

https://github.com/jaleezyy/covid-19-signal/blob/877fa06facf6a9a1db93ef6313d92a3e4353de39/Snakefile#L171

We can just specify that users should provide a single pair of fastq for each sample?

**Comment by jaleezyy** [comment]
Yeah, I'm inclined to agree since that was for some of our earliest samples. I see no reason to keep it any longer. I haven't seen any of our current datasets requiring this step either. Can you confirm @agmcarthur?

**Comment by fmaguire** [comment]
Fixed in v1.1.0
