### ISSUE TITLE
Error when download data dependencies with docker image

### ISSUE THREAD

**Issue by domenico-simone** [jaleezyy/covid-19-signal#104]
Hi,

I have pulled the docker image of the tool and it went fine, but when I try to download data dependencies (just using the command in the README), I get this error:

```
$ mkdir -p data && docker run -v $PWD/data:/data finlaymaguire/signal:1.1.0 bash scripts/get_data_dependencies.sh -d /data

This script requires conda but it looks like you don't have conda activated.
```

Am I missing anything?

Thank you,

Domenico

**Comment by fmaguire** [comment]
Hi @domenico-simone 

This was an issue with the automatic docker build failing.  I've fixed it and now:

```mkdir -p data && docker run -v $PWD/data:/data finlaymaguire/signal:latest bash scripts/get_data_dependencies.sh -d /data```                                                                                                                                         
 
 should work as intended!
