### ISSUE TITLE
Error during host removal

### ISSUE THREAD

**Issue by kdmack87** [jaleezyy/covid-19-signal#105]
Hi there!

I'm getting an error during the host removal step:
`  File "/opt/covid-19-signal/scripts/filter_non_human_reads.py", line 50
    if __name__ == '__main__':
                             ^
SyntaxError: invalid syntax
[M::bwa_idx_load_from_disk] read 0 ALT contigs`

I think there might be an end bracket missing in the line of code prior to line 50.

**Comment by fmaguire** [comment]
Good shout, I added that check for empty read sets late last night and missed that.

Should be fixed now (#93bc296)
