### ISSUE TITLE
Compare freebayes/ivar consensus directly

### ISSUE THREAD

**Issue by fmaguire** [jaleezyy/covid-19-signal#107]
Consider adding https://github.com/jts/ncov-random-scripts/blob/master/quick_align.py to directly compare significant changes between freebayes and ivar consensus genomes

**Comment by jaleezyy** [comment]
Draft currently implemented in [post](https://github.com/jaleezyy/covid-19-signal/tree/post) branch. Currently reporting nucleotide differences in the same format as variant using the FreeBayes consensus sequence as the reference. 

Will close this issue when the final PR is made.

**Comment by fmaguire** [comment]
You are on fire with the SIGNAL upgrade!
