### ISSUE TITLE
Pangolin Update changes probability column to conflict breaking assign_lineages.py

### ISSUE THREAD

**Issue by DarianHole** [jaleezyy/covid-19-signal#110]
Key error occurs when running signal due to the change in the latest pangolin column headers. 
```
File "/Drives/W/Projects/covid-19/analysis_resources/signal_resources/conda/1530aec7/lib/python3.7/site-packages/pandas/core/indexing.py", line 1645, in _validate_read_indexer
    raise KeyError(f"{not_found} not in index")
KeyError: "['pangolin_lineage_probability'] not in index"
[Thu Apr 29 14:49:22 2021]
Error in rule run_lineage_assignment_freebayes:
```
I've gotten past this error with the help of @kdmack87 and it seems to just be changing "probability" to "conflict" on the following line: https://github.com/jaleezyy/covid-19-signal/blob/97f43fcba1e0a1e5aea22c942019d69457f5abcb/scripts/assign_lineages.py#L101

I'm not sure how you want to change the following column names with this though so I've just created this as an issue.

Darian

**Comment by fmaguire** [comment]
Hah I just ran into that exact issue and was in the process of making a commit to fix it!

Should be fixed as of #d2e3654
