### ISSUE TITLE
Primer Scheme Correction

### ISSUE THREAD

**Issue by moreiradaniel** [jaleezyy/covid-19-signal#113]
Hi,

First of all, thanks for the effort to build and maintain the Signal workflow.

There is a small correction to be made (covid-19-signal/resources/primer_schemes/2kb_resende_v2/). I'm working with SARS-CoV-2 data from Resende's Lab and I noticed that the primer sequence (nCoV-2019_2_LEFT) described at https://doi.org/10.1101/2020.04.30.069039 aligns to reference (MN908947.3) from 1925 to 1947 (0-based), instead of 1916:1942.

Best,
Daniel

**Comment by fmaguire** [comment]
Thanks for looking so carefully at this! 

The scheme in the repo is a modified version of the resende scheme by [National Microbiology Lab]( [repo](https://github.com/phac-nml/primer-schemes/tree/master/nCoV-2019/2kb_resende_v2)) to deal with a bit of dropout. I've just added in the original freede scheme from the paper with `nCoV-2019_2_LEFT` 1925:1947 so folks can find both.
