### ISSUE TITLE
RuleException in line 549 of: filepath/Snakefile: 'Params' object has no attribute 'unlabelled_output_dir'

### ISSUE THREAD

**Issue by christinehehnly** [jaleezyy/covid-19-signal#124]
Hey there, I have been having an issue with this since you changed the output directory for breseq and can't figure it out. Any idea?

**Comment by jaleezyy** [comment]
Thanks for letting me know! This is what I get messing with an older rule. Removed the unneeded parameters and quickly looked over the command in the latest commit. Let me know if you're still having problems.

**Comment by jaleezyy** [comment]
Closing this issue since internal tests are no longer coming across this `RuleException`. Let me know if the problem persists!
