### ISSUE TITLE
Artic-ncov2019 primer scheme V5.3.2

### ISSUE THREAD

**Issue by ReemaSingh** [jaleezyy/covid-19-signal#141]
Hi,

I am analyzing a few Illumina datasets using the covid-19-signal pipeline. I would like to use primer scheme v5.3.2. Therefore, I was wondering if it is accurate to use the primer scheme from a separate pipeline i.e., artic-network/artic-ncov2019. I would highly appreciate any comments and suggestions.

Thanks

**Comment by jaleezyy** [comment]
Hi,

Yes, you can use the primer scheme from another pipeline if you desire. To do so would require the `.bed` file defining the scheme. This `.bed` will be used when invoking `ivar trim`. 

Within your `config.yaml` file, you would substitute the following parameter with the corresponding path to the `.bed` file on your system.

```
# Path from snakemake dir to .bed file defining amplicon primer scheme
scheme_bed: 'resources/primer_schemes/artic_v3/nCoV-2019.bed'
```

The path in the example is simply the default and can be changed with any of the scheme we provide (including some from artic-network) or your own. 

Hope this helps.

**Comment by ReemaSingh** [comment]
Thank you so much for your confirmation on this.

**Comment by jaleezyy** [comment]
You're welcome! Feel free to re-open this issue if you come across problems regarding the primer schemes.
