### ISSUE TITLE
Error running get_data_dependencies.sh

### ISSUE THREAD

**Issue by fwhelan** [jaleezyy/covid-19-signal#32]
I ran `bash pipeline/scripts/get_data_dependencies.sh -d data -a MN908947.3` and got the following error:
```
Downloading nucleotide gb accession to taxon map...rsync: failed to connect to ftp.ncbi.nlm.nih.gov (130.14.250.12): Connection timed out (110)
rsync: failed to connect to ftp.ncbi.nlm.nih.gov (2607:f220:41e:250::11): Network is unreachable (101)
rsync error: error in socket IO (code 10) at clientserver.c(127) [Receiver=3.1.3]
```

Looking through the script, I narrowed it down to line 45: `kraken2-build --download-taxonomy --db Kraken2/db --threads 10` When I run that at the commandline, I get the same error as above. Which led me here https://github.com/DerrickWood/kraken2/issues/38. Adding `--use-ftp` solved my issue.

It would also be helpful to add a comment on the estimated disc space needed for these databases & dependencies.

**Comment by fwhelan** [comment]
As an aside/for the record, I then ran into this issue:
```
Downloading nucleotide gb accession to taxon map... done.
Downloading nucleotide wgs accession to taxon map... done.
Downloaded accession to taxon map(s)
Downloading taxonomy tree data... done.
Uncompressing taxonomy data...
gzip: nucl_wgs.accession2taxid.gz: unexpected end of file
```
Which I solved with this: https://github.com/DerrickWood/kraken/issues/45

**Comment by fwhelan** [comment]
Had to add `--use-ftp` to line 46 as well.

**Comment by jaleezyy** [comment]
Given the current version of Kraken2 being used, the issue likely stems from broken ftp links through `kraken2-build` in 2.0.7 (as discussed in https://github.com/jaleezyy/covid-19-sequencing/issues/8#issuecomment-619283811). 

We're working on implementing kraken2 2.0.8.
