### ISSUE TITLE
coverage plot

### ISSUE THREAD

**Issue by agmcarthur** [jaleezyy/covid-19-signal#34]
consider creating an a read coverage plot alternative to that provided by BreSeq, based on the step 13 HiSAT2 results, with y-axis in log scale?

**Comment by jaleezyy** [comment]
Would the HiSAT2 result then substitute the `bedtools genomecov -d` files since both provide a per-base coverage file? Or perhaps the broader question becomes do we cut the `bedtools` to reduce the number of jobs; knock two birds with one stone?

**Comment by agmcarthur** [comment]
I would keep the pipeline as is but use the coverage/depth.text file to make a plot

**Comment by jaleezyy** [comment]
Ah, I might be mixing up output files, the depth.txt is from `bedtools`.

**Comment by agmcarthur** [comment]
Examples in log scale:

![Screen Shot 2020-05-13 at 3 03 14 PM](https://user-images.githubusercontent.com/27361102/81853779-e61c4980-952a-11ea-93f1-06864612d953.png)

**Comment by fmaguire** [comment]
Did you generate this example plot with any particular plotting library/tool?

**Comment by jaleezyy** [comment]
Integrative Genomics Viewer is how the example one was made.

**Comment by nknox** [comment]
Jared's tool does a good job of creating a plot similar to this. 

![image](https://user-images.githubusercontent.com/8161226/82807613-bd128780-9e4d-11ea-9770-12ba251cddc4.png)

**Comment by kmsmith137** [comment]
I modified the postprocessing script to generate coverage plots like the one below. Maybe it would be useful to have it run in the core pipeline, instead of in the postprocessing script?

![coverage](https://user-images.githubusercontent.com/8570972/82813435-0f11d800-9e63-11ea-9f91-6c4144fc24c0.png)

**Comment by agmcarthur** [comment]
Let's use @kmsmith137's plots in the core pipeline.
