### ISSUE TITLE
Running pipeline via docker

### ISSUE THREAD

**Issue by raphenya** [jaleezyy/covid-19-signal#39]
- Running pull command on both Mac OS and Linux i'm getting the following error:
 
```
docker pull finlaymaguire/pipeline
Using default tag: latest
Error response from daemon: pull access denied for finlaymaguire/pipeline, repository does not exist or may require 'docker login'
```

- Running build on Mac OS using `docker build -f Dockerfile_pipeline .` gave error:

```
Solving environment: ...working... The command '/bin/sh -c conda create --name snakemake --channel conda-forge --channel bioconda snakemake=5.11.2' returned a non-zero code: 137
```

**Comment by fmaguire** [comment]
`docker pull finlaymaguire/sars-cov2-pipeline` is the correct path now, should be update to signal.

As for the build failing on mac osx... no idea but it works on my system and a clean ubuntu instance.

**Comment by jaleezyy** [comment]
Can confirm that `docker pull finlaymaguire/sars-cov2-pipeline` works @raphenya.

**Comment by fmaguire** [comment]
Pending finishing building and being deployed this is now updated to `docker pull finlaymaguire/signal`

**Comment by raphenya** [comment]
> Can confirm that `docker pull finlaymaguire/sars-cov2-pipeline` works @raphenya.

Pull is working for me now.

**Comment by fmaguire** [comment]
Just double checked and `docker pull finlaymaguire/signal` works now.  

The docker build fail on Mac OSX seems to be something to do with the networking proxy https://github.com/docker/for-mac/issues/2174#issuecomment-339739436 not going to fix that. Mac users can pull the built container instead.
