### ISSUE TITLE
Add primer QC check

### ISSUE THREAD

**Issue by fmaguire** [jaleezyy/covid-19-signal#41]
Do a QC for primers after trimming to make sure there aren't any remaining

**Comment by jaleezyy** [comment]
Added our primer counting script to `resources/dev_scripts/primer_finder.py`.

**Comment by fmaguire** [comment]
Would `grep -c -f $primer_file` be a quick easy way to achieve the same core function as the script?

**Comment by jaleezyy** [comment]
.........yes, yes it would. 😂 

`grep -c -f $rc_primer_file R1.fastq`
`grep -c -f $fw_primer_file R2.fastq`

...would give what the script outputs as summary.
