### ISSUE TITLE
Run ncov-tools pipeline on output

### ISSUE THREAD

**Issue by fmaguire** [jaleezyy/covid-19-signal#43]
Add pipeline support for running https://github.com/jts/ncov-tools

Issue created at ncov-tools repo: https://github.com/jts/ncov-tools/issues/2

**Comment by jaleezyy** [comment]
Maybe add to Snakemake postprocess protocol?

**Comment by agmcarthur** [comment]
Extra bonus of using ncos-tools is ability to generate multiple sequence alignments that also include GISAID data, but can we ask @jts to add masking of http://virological.org/t/issues-with-sars-cov-2-sequencing-data/473

**Comment by agmcarthur** [comment]
The amplicon coverage figure compress the results of all samples into a single image, making resolution poor. Any chance of also generating a separate image for each sample?

**Comment by jts** [comment]
The latest version of ncov-tools will put 8 coverage plots per page, so hopefully that will look a bit better now?

**Comment by agmcarthur** [comment]
@nknox can you see if the 8 coverage plots per page works better for PHAC? Thanks.

**Comment by fmaguire** [comment]
Working on this: plan is to add as a submodule (so recursive git clone of repo will clone) and then modifying @kmsmith137 post-processing script to prepare and run files through the pipeline.

Currently having issues with the included env not solving but will see if I can work out what the issue is tomorrow.

**Comment by nknox** [comment]
> @nknox can you see if the 8 coverage plots per page works better for PHAC? Thanks.

Yes looks better now!
