### ISSUE TITLE
adjust Trimmomatic options

### ISSUE THREAD

**Issue by raphenya** [jaleezyy/covid-19-signal#46]
There are short sequences in fastqs after Trimmomatic step we should update to specify lengths:
```
ILLUMINACLIP: Cut adapter and other illumina-specific sequences from the read.
SLIDINGWINDOW: Perform a sliding window trimming, cutting once the average quality within the window falls below a threshold.
LEADING: Cut bases off the start of a read, if below a threshold quality
TRAILING: Cut bases off the end of a read, if below a threshold quality
CROP: Cut the read to a specified length
HEADCROP: Cut the specified number of bases from the start of the read
MINLEN: Drop the read if it is below a specified length
TOPHRED33: Convert quality scores to Phred-33
TOPHRED64: Convert quality scores to Phred-64
```

**Comment by jaleezyy** [comment]
Need considerations on minimum length. Should be greater length than primer to avoid zero-length sequence outputs after primer trimming.

**Comment by fmaguire** [comment]
So, in the consensus pipeline branch (i.e. moving towards common core tools + our extra analyses) we are now using trim_galore (auto detects primers and using cutadapt at core).

Principle params (specified in config) min_qual and min_len
