### ISSUE TITLE
new summary visualization - %SARS versus completeness

### ISSUE THREAD

**Issue by agmcarthur** [jaleezyy/covid-19-signal#48]
I've been using this pipeline and making this summary plot based on the output statistics. The label for the sample is "Sample Name, Average Fold Coverage".

![Screen Shot 2020-05-13 at 3 19 42 PM](https://user-images.githubusercontent.com/27361102/81855368-44e2c280-952d-11ea-8bd6-91a63023fdbf.png)

It would be great if this summary figure was generated automatically.

**Comment by fmaguire** [comment]
Which tool outputs are you grabbing these stats from?

**Comment by jaleezyy** [comment]
If you're asking for the plot itself, as I learned recently, probably https://scatterplot.online

**Comment by kmsmith137** [comment]
First version of this added. Note that I'm taking (% SARS-Cov-2) from Kraken2 and (genome fraction) from Quast.  Let me know if this is not the right thing to do!

![summary](https://user-images.githubusercontent.com/8570972/82813255-af1b3180-9e62-11ea-87f8-b46f54fafe47.png)

**Comment by fmaguire** [comment]
Looks perfect, nicely done @kmsmith137 !

**Comment by agmcarthur** [comment]
Perfect @kmsmith137
