### ISSUE TITLE
c19_postprocess script needs updating

### ISSUE THREAD

**Issue by nknox** [jaleezyy/covid-19-signal#54]
Need to swap cutadapt parsing for trim galore and ivar trim. Also need to change the directory where Fastqc files are found post-trimming. May want to run fastqc after ivar trim instead.

**Comment by kmsmith137** [comment]
I did the trim_galore parsing and updated the fastqc directory. Leaving this issue open, since I didn't want to lose track of Natalie's suggestion to run fastqc after ivar trim.

**Comment by fmaguire** [comment]
Think there is still utility of running fastqc on the reads after quality and adapter trimming to check the quality trimming is reasonable (plus trim_galore makes it essentially free) as well as for just those that mapped to reference (and had primers removed). 

So I added another fastqc run making 3 totals:
1. raw reads
2. reads without seq adapters and low quality removed
3. trimmed reads which mapped to the viral reference and have had the primer sequences removed,

**Comment by nknox** [comment]
Fastqc HTML report should not include "sequence duplication" or "overrepresented sequence" flags as these will generally fail with an amplicon-based protocol.
