### ISSUE TITLE
RuntimeWarning for generated figures

### ISSUE THREAD

**Issue by raphenya** [jaleezyy/covid-19-signal#59]
scripts/c19_postprocess.py:1075: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).

**Comment by kmsmith137** [comment]
I think this is fixed now! Can you confirm? I don't have a pipeline instance handy with enough samples to trigger the warning!
