### ISSUE TITLE
Snakemake/Conda install issues (temporary solution?)

### ISSUE THREAD

**Issue by jaleezyy** [jaleezyy/covid-19-signal#60]
In attempting to create the conda environment with `snakemake`:
```
$ conda create -c conda-forge -c bioconda -n snakemake snakemake pandas
$ conda activate snakemake
(snakemake) $ snakemake --version
5.3.0
(snakemake) $
```
So firstly, the channels need to be specified or else it fails to find `snakemake`.
Secondly, the "latest" version of `snakemake` found is 5.3.0 (5.11.2 not even found, hence why the version is not specified in the above command...**which may or may not be a typo...**).
Apparently this is a [known problem](https://github.com/conda/conda/issues/9905).

The following can be seen at [the installation instructions in the Snakemake documentation](https://snakemake.readthedocs.io/en/stable/getting_started/installation.html):

```
conda install -c conda-forge mamba # install workaround mamba
mamba create -c conda-forge -c bioconda -n snakemake snakemake # create conda environment using mamba, installing snakemake
conda activate snakemake 
```
Temporary rewording of instuctions to install `snakemake` through this alternate method? ...at least until conda catches up?

**Comment by raphenya** [comment]
This worked for me by specifying version:
`conda create -c conda-forge -c bioconda -n snakemake snakemake=5.11.2 pandas`

Then I get this error when running the pipeline: 
```
Building DAG of jobs...
Creating conda environment conda_envs/ivar.yaml...
Downloading and installing remote packages.
Environment for conda_envs/ivar.yaml created (location: .snakemake/conda/1058a4d9)
Creating conda environment conda_envs/snp_mapping.yaml...
Downloading and installing remote packages.
CreateCondaEnvironmentException:
Could not create conda environment from /workspace/raphenar/sars-cov-2/covid-19-sequencing/conda_envs/snp_mapping.yaml:
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed
ResolvePackageNotFound: 
  - ld_impl_linux-64==2.34=h53a641e_0
  - binutils_impl_linux-64==2.34=h53a641e_0
```

**Comment by raphenya** [comment]
I re-created the environment with python version 3.6 then I got:
```
Building DAG of jobs...
Creating conda environment conda_envs/trim_qc.yaml...
Downloading and installing remote packages.
CreateCondaEnvironmentException:
Could not create conda environment from /workspace/raphenar/sars-cov-2/covid-19-sequencing/conda_envs/trim_qc.yaml:
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed

ResolvePackageNotFound: 
  - ld_impl_linux-64==2.34=h53a641e_0
```

Searching the condo channels the build number is wrong in the yaml file:

```
conda search ld_impl_linux-64 -c bioconda -c defaults -c conda-forge
Loading channels: done
# Name                       Version           Build  Channel             
ld_impl_linux-64                2.32               5  conda-forge         
ld_impl_linux-64                2.32      h53a641e_6  conda-forge         
ld_impl_linux-64              2.33.1               5  conda-forge         
ld_impl_linux-64              2.33.1      h53a641e_6  conda-forge         
ld_impl_linux-64              2.33.1      h53a641e_7  pkgs/main           
ld_impl_linux-64              2.33.1      h53a641e_7  conda-forge         
ld_impl_linux-64              2.33.1      h53a641e_8  conda-forge         
ld_impl_linux-64                2.34      h53a641e_2  conda-forge     
```
I will update the build number and see if this error goes away.

**Comment by raphenya** [comment]
Same package with wrong build number for a different yaml file:

```
Building DAG of jobs...
Creating conda environment conda_envs/trim_qc.yaml...
Downloading and installing remote packages.
Environment for conda_envs/trim_qc.yaml created (location: .snakemake/conda/b49a1142)
Creating conda environment conda_envs/ivar.yaml...
Downloading and installing remote packages.
Environment for conda_envs/ivar.yaml created (location: .snakemake/conda/1058a4d9)
Creating conda environment conda_envs/assembly_qc.yaml...
Downloading and installing remote packages.
CreateCondaEnvironmentException:
Could not create conda environment from /workspace/raphenar/sars-cov-2/covid-19-sequencing/conda_envs/assembly_qc.yaml:
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed

ResolvePackageNotFound: 
  - ld_impl_linux-64==2.34=h53a641e_0
```

@fmaguire @kmsmith137 should we not specify build numbers?

**Comment by fmaguire** [comment]
This is related to the issue I made yesterday. Basically, conda is a great
installer and a terrible historical dependency system because they remove
old packages.

Basically, the envs should be stripped down to the core tools we actually
use (ideally with version specified for reproducing) and the other
dependencies should be managed as conda sees fit.

This should make things a bit more stable and easy to maintain over time as
there are fewer 'hard coded' dependencies.

**Comment by jaleezyy** [comment]
Updating the build (or letting conda make some decisions in which build to install) restored functionality.

**Comment by jaleezyy** [comment]
Simplifying the env files would definitely make things easier as per [58](https://github.com/jaleezyy/covid-19-signal/issues/58).

**Comment by fmaguire** [comment]
rgi installation has had similar issues as well with versions
