### ISSUE TITLE
breseq reference 'MN908947_primer_annotated_prot_clinical.gb' not included in data dependencies

### ISSUE THREAD

**Issue by dfornika** [jaleezyy/covid-19-signal#83]
The `example_config.yaml` file refers to a file called `MN908947_primer_annotated_prot_clinical.gb` that is used as a reference for `breseq`, but that file isn't provided by the `get_data_dependencies.sh` script.

Could it be added to that script? Or if not, could a note be added to the `README.md` describing where to find that file?

**Comment by jaleezyy** [comment]
Ah, that file is a custom-made genbank file of the MN908947.3 reference with additional regions highlighted. The `get_data_dependencies.sh` should grab a `.gbk` file of the desired accession, which can be used in place of `MN908947_primer_annotated_prot_clinical.gb`. 

I'll edit the example_config.yaml to reflect `get_data_dependencies.sh` output files.

**Comment by jaleezyy** [comment]
Edits to `example_config.yaml` made in commit [f4962df](https://github.com/jaleezyy/covid-19-signal/commit/f4962dfabf5a10b7baffabb92c101da1279612df)

**Comment by dfornika** [comment]
Thanks! That should prevent the pipeline from failing. I'm still a bit curious to know about the custom annotations and how our output might be affected by using the original MN908947.3 genbank. Is the specially-annotated reference used for any of the post-processing steps?

**Comment by jaleezyy** [comment]
No reference (custom, or otherwise) is hard-coded in any post-processing step. All analysis and output is relative to the provided references in the `config.yaml`.

**Comment by dfornika** [comment]
Thanks! I'll close this.
