### ISSUE TITLE
host removal step produces empty fastqs

### ISSUE THREAD

**Issue by raphenya** [jaleezyy/covid-19-signal#85]
host removal step produces empty fastqs as a results trim_galore fails with the following log:
```
cat results_dir/S4/adapter_trimmed/S4_trim_galore.log
Path to Cutadapt set as: 'cutadapt' (default)
Cutadapt seems to be working fine (tested command 'cutadapt --version')
Cutadapt version: 2.10
Could not detect version of Python used by Cutadapt from the first line of Cutadapt (but found this: >>>#!/bin/sh<<<)
Letting the (modified) Cutadapt deal with the Python version instead
Parallel gzip (pigz) detected. Proceeding with multicore (de)compression using 2 cores

No quality encoding type selected. Assuming that the data provided uses Sanger encoded Phred scores (default)

Output will be written into the directory: /workspace/raphenar/sars-cov-2/covid-19-sequencing/results_dir/S4/adapter_trimmed/
Input file 'S4/host_removal/S4_R1.fastq.gz' seems to be completely empty. Consider respecifying!
```

**Comment by fmaguire** [comment]
Ah damn, apparently samtools just throws away all reads with <30mapq when using `-q` instead of marking them unmapped.  Previously we were filtering on the bwa alignment score not technically the mapq as Jared pointed out, I was still testing out the change.  Shouldn't be a major issue but now we need some new code because samtools only has options to keep mapq>=x not <=x.

**Comment by jts** [comment]
With `-U` you can redirect the reads that fail the filter into a different bam

**Comment by fmaguire** [comment]
...yup, I think I might be overextending myself a bit between too many coding projects at the same time just now.  Cheers @jts I've made the change so it should be removing MAPQ<30. 

This is more permissive than the original filter that removed any read that mapped to the human reference (as I'd misinterpreted the internal "score" from bwa).  Looking at kraken2 reports ~10x more reads that it classifies as "human" than before. So double check and see what you think.

As I said on the original issue discussion, this all still needs looked at more systematically than "the few test isolates I had to hand" using a diverse representative set of illumina sequences. I don't really have time to gather that dataset but happy to do the analysis if someone else has/does.  Will/BCCDC mentioned having a dataset like that but didn't follow up and I didn't chase them.

**Comment by raphenya** [comment]
Ok, bug resolved. @fmaguire For datasets we just need the `*_human_mapping_reads.bam` to compare across samples?

**Comment by raphenya** [comment]
| SAMPLE  | OLD  (MB)|  NEW (MB) |
  | -- | -- | -- |
  | S357   |  48 | 12 |
  | S65 | 58 | 16 |
 | S4  | 61 |  9.3

comparing the size of `*_human_mapping_reads.bam` files from old pipeline to new changes

**Comment by fmaguire** [comment]
@jts and I have been looking at this/discussing this more, and it looks like @jts 's original suggestion of using a composite reference of host and viral and letting competitive mapping do its job might be a better option. I've made a branch to do it this way:

https://github.com/jaleezyy/covid-19-signal/tree/composite_ref

But still having some issues with resolving reads that have multiple alignments even after filtering for secondary/supplemental alignments e.g. 

```NS500345:342:HMJ5NBGXF:1:22308:21863:5001 NC_000002.12 mapq=1 ref_len=36 Read=R1
NS500345:342:HMJ5NBGXF:1:22308:21863:5001 MN908947.3 mapq=1 ref_len=36 Read=R1
NS500345:342:HMJ5NBGXF:1:22308:21863:5001 MN908947.3 mapq=60 ref_len=40 Read=R2```

I've followed up with Jun in Will's group re: a representative benchmarking set and they just have all the SARS-COV2 SRA files so far.  They were suggesting randomly selecting 150-250 -> assembly -> lineage -> for each clade select highest coverage/depth as representative -> filter down to 10-30 samples.  Will be biased towards diversity in countries with more active sequencing however.

Alternatively, someone would have to do the manual selecting and backtracking from nextstrain etc to SRA.  Would be a bit arbitrary and manually intensive (although far less computationally so).

**Comment by fmaguire** [comment]
The issue was a mistake in my conditional for filtering supplemental/secondary alignments https://github.com/jaleezyy/covid-19-signal/commit/a700363376b1d2a30bca3b7ac31745bacde4dbfa 

Just testing the complete run through before merging to master.
