### ISSUE TITLE
config.yaml is an argument to snakemake, yet overriding with another config file name fails

### ISSUE THREAD

**Issue by nodrogluap** [jaleezyy/covid-19-signal#91]
It would be nice to clarify if the intention is that the config.yaml file must be named so, or if the --configfile argument is superfluous. Personally I think it would be nice to be able to have differently named YAML files for each run stored in one place, and use the --configfile argument. Thanks!

```terminal
(signal) -bash-4.2$ snakemake -kp --configfile config_AB_run2.yaml --cores=32 --use-conda all --conda-prefix=$PWD/.snakemake/conda
WorkflowError in line 29 of /home/gordonp/covid-19-signal/Snakefile:
Config file config.yaml not found.
  File "/home/gordonp/covid-19-signal/Snakefile", line 29, in <module>
```

**Comment by jaleezyy** [comment]
Modified the Snakefile in commit [021cb84](https://github.com/jaleezyy/covid-19-signal/commit/021cb84a56c01f7bbd35c1e80e716e3ad5cf896f).

This should allow for alternate config files to be used through the `snakemake --configfile` argument. Should work with relative and absolute paths of the config file. A copy of the config file will be placed in the results directory.

**Comment by jaleezyy** [comment]
Secondary change to initial path to config file in commit [9189858](https://github.com/jaleezyy/covid-19-signal/commit/91898582a2c164256e40759124dd09fb9c2e4351)

Should now work if you run the above command in your example.

**Comment by jaleezyy** [comment]
Will close for now unless there are other issues with using alternate config files.
