### ISSUE TITLE
Update ncov-tools integration with SIGNAL

### ISSUE THREAD

**Issue by jaleezyy** [jaleezyy/covid-19-signal#97]
As [ncov-tools](https://github.com/jts/ncov-tools) continues its development with the addition of new features and analyses, attempting to run SIGNAL with an older ncov-tools submodule is becoming less optimal. 

We'll need to update the ncov-tools config.yaml generated through our own scripts and execution of a more up-to-date version of ncov-tools.

**Comment by fmaguire** [comment]
Should be updated as of the param update.

I've also symlinked the ncov config so it should always be in sync with the submodule.

**Comment by jaleezyy** [comment]
The current submodule commit I see is `6f87afd` which is dated back in June? 

You've symlinked the environment, which will ensure we always have the capacity to run ncov-tools, but the actual `config.yaml` (for ncov-tools, not SIGNAL) generated using `ncov-tools.py` is out of date, so we'd only be able to functionally call `all_qc_sequencing` and `all_qc_analysis` but we are currently missing`all_qc_reports` and likely `annotate_variants`.

**Comment by fmaguire** [comment]
Ah fair point, sorry was having a brainfart when I followed the link and totally didn't notice I wasn't as HEAD.

**Comment by jaleezyy** [comment]
No worries! Simply adding this issue since I noticed us running ncov-tools manually lately. Kinda defeats the purpose of integration if we're running it manually instead because SIGNAL isn't providing all the reports! 😂

**Comment by fmaguire** [comment]
Given issues with conda envs not staying isolated for some reason: we might be best served by just running ncov-tools via singularity and the new container.
